apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: tensorflow3
  annotations: 
    serving.kserve.io/enable-metric-aggregation:  "true"
    serving.kserve.io/enable-prometheus-scraping: "true"

spec:
  predictor:
    tensorflow:
      storageUri: https://raw.githubusercontent.com/anupamababu1984/kserve-tensorflow/main/saved_model3.zip
