# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KyQQ1WwWl7lRNU3zqWrDEz_D8_Re-ivK
"""

import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np

# Load the saved model
model = tf.keras.models.load_model('/content/drive/MyDrive/my_model.h5')

# Define the path to the custom image
custom_image_path = '/content/drive/MyDrive/CT Image/benign.png'  # Replace this with the path to your custom image

# Preprocess the image
img = image.load_img(custom_image_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.  # Rescale pixel values to [0, 1]

# Perform inference
predictions = model.predict(img_array)

# Decode predictions
if np.argmax(predictions) == 0:
    predicted_class = 'malignant'
else:
    predicted_class = 'benign'

print("Predicted class:", predicted_class)

# Run pip freeze and save output to requirements.txt
!pip freeze > requirements.txt

# Move requirements.txt to Google Drive
import shutil
shutil.move("requirements.txt", "/content/drive/MyDrive/requirements.txt")